version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: autoria_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=autoria
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - JWT_EXPIRATION=1d
    depends_on:
      - postgres
    networks:
      - autoria_network

  postgres:
    image: postgres:14-alpine
    container_name: autoria_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autoria
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autoria_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: autoria_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@autoria.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - autoria_network

  redis:
    image: redis:alpine
    container_name: autoria_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - autoria_network

networks:
  autoria_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
